apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: ingress
  metrics:
  - name: success-rate
    interval: 20s
    successCondition: result[0] > 0.95
    provider:
      prometheus:
        address: http://prometheus-operator-prometheus.monitoring:9090
        query: >+
          sum(
            rate(traefik_backend_requests_total{service="{{args.backend}}",code!~"[4-5].*"}[40s]))
            /
            sum(rate(traefik_backend_requests_total{service="{{args.backend}}"}[40s])
          )
