apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: backend
  metrics:
  - name: success-rate
    interval: 20s
    successCondition: result[0] = 0
    provider:
      prometheus:
        address: http://prometheus-operator-prometheus.monitoring:9090
        query: >+
          rate(traefik_backend_requests_total{backend="{{args.backend}}",code!~"[4-5].*"}[40s])

